#!/usr/bin/env python3
"""
analyze_gt_contacts.py – Inspect ground‑truth contact label files
generated by generate_contact_labels.py.
"""

import argparse
import sys
from pathlib import Path
import numpy as np


def analyze_label_file(npz_path: Path, verbose: bool = False) -> dict:
    """Analyze a single label .npz file. Returns stats dict."""
    try:
        data = np.load(npz_path)
    except Exception as e:
        print(f"  ERROR loading {npz_path}: {e}")
        return None

    stats = {
        "path": str(npz_path),
        "left_contact_count": 0,
        "right_contact_count": 0,
        "left_total": 0,
        "right_total": 0,
        "left_ratio": 0.0,
        "right_ratio": 0.0,
    }

    if "left_contact" in data:
        left = data["left_contact"]
        stats["left_total"] = left.size
        stats["left_contact_count"] = left.sum()
        stats["left_ratio"] = left.mean() if left.size > 0 else 0.0
    else:
        print(f"  Warning: 'left_contact' missing in {npz_path}")

    if "right_contact" in data:
        right = data["right_contact"]
        stats["right_total"] = right.size
        stats["right_contact_count"] = right.sum()
        stats["right_ratio"] = right.mean() if right.size > 0 else 0.0
    else:
        print(f"  Warning: 'right_contact' missing in {npz_path}")

    if verbose:
        # Print per‑frame details
        print(f"\n{npz_path.name}:")
        print(f"  left_contact: {stats['left_contact_count']}/{stats['left_total']} ({stats['left_ratio']*100:.2f}%)")
        print(f"  right_contact: {stats['right_contact_count']}/{stats['right_total']} ({stats['right_ratio']*100:.2f}%)")

    return stats


def analyze_directory(dir_path: Path, pattern: str = "frame_*.npz", verbose: bool = False):
    """Analyze all label files in a directory."""
    files = sorted(dir_path.glob(pattern))
    if not files:
        print(f"No files matching '{pattern}' in {dir_path}")
        return []

    print(f"Found {len(files)} label files.")
    all_stats = []
    for f in files:
        stats = analyze_label_file(f, verbose=verbose)
        if stats:
            all_stats.append(stats)

    return all_stats


def summarize_stats(all_stats: list):
    """Print summary across all frames."""
    if not all_stats:
        print("No valid stats to summarize.")
        return

    left_ratios = [s["left_ratio"] for s in all_stats if s["left_total"] > 0]
    right_ratios = [s["right_ratio"] for s in all_stats if s["right_total"] > 0]

    print("\n" + "="*60)
    print("SUMMARY ACROSS ALL FRAMES")
    print("="*60)
    if left_ratios:
        print(f"Left hand  - Mean contact ratio: {np.mean(left_ratios)*100:.2f}%  (std={np.std(left_ratios)*100:.2f}%)")
        print(f"             Min: {np.min(left_ratios)*100:.2f}%, Max: {np.max(left_ratios)*100:.2f}%")
        # Count frames with any contact
        frames_with_left = sum(1 for r in left_ratios if r > 0)
        print(f"             Frames with any left contact: {frames_with_left} / {len(left_ratios)}")
    else:
        print("Left hand: no data")

    if right_ratios:
        print(f"Right hand - Mean contact ratio: {np.mean(right_ratios)*100:.2f}%  (std={np.std(right_ratios)*100:.2f}%)")
        print(f"             Min: {np.min(right_ratios)*100:.2f}%, Max: {np.max(right_ratios)*100:.2f}%")
        frames_with_right = sum(1 for r in right_ratios if r > 0)
        print(f"             Frames with any right contact: {frames_with_right} / {len(right_ratios)}")
    else:
        print("Right hand: no data")

    # Optional: total contact vertices averaged across frames
    if left_ratios:
        avg_left_contacts = np.mean([s["left_contact_count"] for s in all_stats])
        print(f"\nAverage number of left contact vertices per frame: {avg_left_contacts:.1f} / 778")
    if right_ratios:
        avg_right_contacts = np.mean([s["right_contact_count"] for s in all_stats])
        print(f"Average number of right contact vertices per frame: {avg_right_contacts:.1f} / 778")


def print_npz_contents(
    npz_path: Path,
    *,
    keys: list[str] | None = None,
    max_elements: int = 50,
    full: bool = False,
) -> None:
    """Print the actual contents of an .npz file.

    By default, prints a small preview per key (shape/dtype + first N values).
    Use full=True to print entire arrays (may be very large).
    """
    try:
        data = np.load(npz_path, allow_pickle=True)
    except Exception as e:
        print(f"ERROR loading {npz_path}: {e}")
        return

    available_keys = list(data.keys())
    if not available_keys:
        print(f"{npz_path}: no arrays found")
        return

    selected_keys = keys if keys is not None else available_keys
    missing = [k for k in selected_keys if k not in data]
    if missing:
        print(f"Warning: missing keys in {npz_path.name}: {missing}")

    print("\n" + "=" * 60)
    print(f"NPZ CONTENTS: {npz_path}")
    print("=" * 60)
    print(f"Keys ({len(available_keys)}): {available_keys}")

    for k in selected_keys:
        if k not in data:
            continue
        arr = data[k]
        print("\n" + "-" * 60)
        print(f"{k}")
        if isinstance(arr, np.ndarray):
            print(f"  shape={arr.shape}, dtype={arr.dtype}")
            if arr.size == 0:
                print("  (empty array)")
                continue

            # Summary stats for numeric-ish arrays.
            if np.issubdtype(arr.dtype, np.number) and arr.size > 0:
                # Avoid warnings on NaNs.
                with np.errstate(all="ignore"):
                    arr_min = np.nanmin(arr)
                    arr_max = np.nanmax(arr)
                    arr_mean = np.nanmean(arr)
                print(f"  min={arr_min}, max={arr_max}, mean={arr_mean}")

            # For bool/int labels, show unique counts if cheap.
            if arr.size <= 5_000 and (arr.dtype == np.bool_ or np.issubdtype(arr.dtype, np.integer)):
                unique, counts = np.unique(arr, return_counts=True)
                pairs = ", ".join([f"{u}: {c}" for u, c in zip(unique.tolist(), counts.tolist())])
                print(f"  value_counts: {pairs}")

            if full:
                print(f"  values:\n{arr}")
            else:
                flat = arr.reshape(-1)
                n = min(max_elements, flat.size)
                preview = flat[:n]
                print(f"  preview_first_{n}: {preview}")
                if flat.size > n:
                    print(f"  ... ({flat.size - n} more elements)")
        else:
            print(f"  (non-ndarray) type={type(arr)}")
            print(f"  value={arr}")


def main():
    parser = argparse.ArgumentParser(description="Analyze ground‑truth contact label files from generate_contact_labels.py")
    parser.add_argument("input", type=str, help="Path to a single .npz file or a directory containing frame_*.npz files")
    parser.add_argument("--pattern", default="frame_*.npz", help="Glob pattern for label files (default: frame_*.npz)")
    parser.add_argument("--verbose", "-v", action="store_true", help="Print per‑frame statistics")
    parser.add_argument("--summary_only", action="store_true", help="Only print summary, not per‑frame details")
    parser.add_argument(
        "--contents",
        action="store_true",
        help="Print the actual arrays stored in a single .npz file (keys/shapes + a preview)",
    )
    parser.add_argument(
        "--full",
        action="store_true",
        help="With --contents, print full arrays (can be very large)",
    )
    parser.add_argument(
        "--max_elements",
        type=int,
        default=50,
        help="With --contents, number of elements to preview per array (default: 50)",
    )
    args = parser.parse_args()

    in_path = Path(args.input)
    if not in_path.exists():
        sys.exit(f"Error: {in_path} does not exist.")

    if in_path.is_file():
        if args.contents:
            print_npz_contents(in_path, max_elements=args.max_elements, full=args.full)
            return
        stats = analyze_label_file(in_path, verbose=True)
        if stats and not args.summary_only:
            # Already printed in verbose mode
            pass
    else:
        if args.contents:
            files = sorted(in_path.glob(args.pattern))
            if not files:
                print(f"No files matching '{args.pattern}' in {in_path}")
                return
            for f in files:
                print_npz_contents(f, max_elements=args.max_elements, full=args.full)
            return
        all_stats = analyze_directory(in_path, pattern=args.pattern, verbose=args.verbose and not args.summary_only)
        if all_stats:
            summarize_stats(all_stats)
        else:
            print("No data to summarize.")


if __name__ == "__main__":
    main()